[global]
# Global configuration affecting all hosts

# Flake url to use as a blue print to build up
# flake = "github:kuutamolabs/near-staking-knd"


[hosts]
[hosts.example]
# Ipv4 address of the node
# ipv4_address = "111.11.11.11"

# Ipv4 gateway of the node
# ipv4_gateway = "111.11.11.254"

# Ipv4 CIDR of the node
# ipv4_cidr = 24

# Nixos module will deploy to the node
# nixos_module = "single-node-validator-testnet"

# Extra nixos module will deploy to the node
extra_nixos_modules = []

# Mac address of the node
# mac_address = ""

# Network interface of the node
# interface = ""

# Ipv6 address of the node
# ipv6_address = ""

# Ipv6 gateway of the node
# ipv6_gateway = ""

# Ipv6 cidr of the node
# ipv6_cidr = 0

# The ssh public keys of the user
# After installation the user could login as root with the corresponding ssh private key
public_ssh_keys = ""

# Admin user for install,
# Please use `ubuntu` when you use OVH to install at first time,
# Ubuntu did not allow `root` login
# install_ssh_user = "ubuntu"

# Setup ssh host name for connection and host label on monitoring dashboard
# ssh_hostname = ""

# Validator key will use in the validator node
# validator_key_file = "validator_key.json"

# Validator node key will use in the node
# validator_node_key_file = "node_key.json"

# Disk configure on the node
# disks = ["/dev/vdb",]

# load configure from encrypt app file
# encrypted_kuutamo_app_file = "hello.pool.devnet.zip"

# Token file for monitoring, default is "kuutamo-monitoring.token"
# Provide this if you have a different file
# kuutamo_monitoring_token_file = "kuutamo-monitoring.token"

# Self monitoring server
# The url should implements [Prometheus's Remote Write API] (https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_write).
# self_monitoring_url = "https://my.monitoring.server/api/v1/push"

# The http basic auth username to access self monitoring server
# self_monitoring_username = ""

# The http basic auth password to access self monitoring server
# self_monitoring_password = ""


