# This is a exmaple kneard-mgr will use to deploy or interact a node
[global]
flake = "github:kuutamolabs/near-staking-knd"

# The keys for ssh
[host_defaults]
public_ssh_keys = [ '''ssh-rsa AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA= someone@laptop
''',
"ssh-ed25519 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA someone@laptop",
]

# admin user for install, Please use ubuntu when you use OVH to install at first time
# Ubunut did not allow root login
install_ssh_user = "ubuntu"
nixos_module = "single-node-validator-testnet"

[hosts]
[hosts.validator-00]
ipv4_address = "111.11.11.11"
ipv4_cidr = 24
ipv4_gateway = "111.11.11.254"
ipv6_address = "2001:1111:1111:1111::1"
ipv6_cidr = 64
ipv6_gateway = "2001:1111:1111:1111:00ff:00ff:00ff:00ff"
validator_key_file = "validator_key.json"
validator_node_key_file = "node_key.json"
