version: 2
updates:
  - package-ecosystem: "github-actions"
    target-branch: "dev"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    target-branch: "dev"
    directory: "/"
    schedule:
      interval: "weekly"
