# Debug nixos test interactively, i.e. `just debug-test kuutamod`
debug-test TEST:
  nix build ../../../#checks.x86_64-linux.{{TEST}}.driver -L
  # Now type start_all() to launch all virtual machines
  # Type server.shell_interact() to get a shell
  ./result/bin/nixos-test-driver -I

# Run a single test locally
run-test TEST:
  nix build ../../../#checks.x86_64-linux.{{TEST}} -L

# Regenerate flake used during the test
generate-test-flake:
  rm -rf test-flake
  cargo run --bin kneard-deploy -- --config ./test-config.toml generate-config test-flake
  git add test-config.toml test-flake
