# This file has been generated by node2nix 1.11.1. Do not edit!

{ nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? [ ] }:

let
  sources = {
    "@near-js/accounts-1.0.2" = {
      name = "_at_near-js_slash_accounts";
      packageName = "@near-js/accounts";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@near-js/accounts/-/accounts-1.0.2.tgz";
        sha512 = "KpyY9r+f55vJ0XCk17vyHeiiNbsmKY9T3ztXKLWQEr661XWJKyetQUBb3dyehf6DHXXnlxwwQNdYDK8d0x1nOQ==";
      };
    };
    "@near-js/crypto-1.2.0" = {
      name = "_at_near-js_slash_crypto";
      packageName = "@near-js/crypto";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@near-js/crypto/-/crypto-1.2.0.tgz";
        sha512 = "iYpiynirW1cB9kNttSsbNhlN4LFR1Esq08aIFyFB/qGNy8DjLYYoe2g923YBxDbVMI6Ljk6AX3G+KDnG3S9lqg==";
      };
    };
    "@near-js/keystores-0.0.8" = {
      name = "_at_near-js_slash_keystores";
      packageName = "@near-js/keystores";
      version = "0.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@near-js/keystores/-/keystores-0.0.8.tgz";
        sha512 = "H3JQroNbx0AvNpXsGiDdjVZCFPqd6Qx29XK618GhwSqvvmFQxq96sh51dmPhJ+jVxFUTt7Q9es8fujYbZceAzw==";
      };
    };
    "@near-js/keystores-browser-0.0.8" = {
      name = "_at_near-js_slash_keystores-browser";
      packageName = "@near-js/keystores-browser";
      version = "0.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@near-js/keystores-browser/-/keystores-browser-0.0.8.tgz";
        sha512 = "ZWBbioO2TUdMkHbmHpwo+DC4CC9XAvS9umIBNgS1XBsY2y3NsG+dWU4bEiFC37fGBzJL9EFw+QJ6RxB+jeOfdQ==";
      };
    };
    "@near-js/keystores-node-0.0.8" = {
      name = "_at_near-js_slash_keystores-node";
      packageName = "@near-js/keystores-node";
      version = "0.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@near-js/keystores-node/-/keystores-node-0.0.8.tgz";
        sha512 = "wiVcKljXi7YkHyQrg1Aw7HubmSGRpC+jNgjCdNBd645Qr9YuSLr/OGTCdliO4QWalU+lUgBV63eSxzAMeUa3Aw==";
      };
    };
    "@near-js/providers-0.0.10" = {
      name = "_at_near-js_slash_providers";
      packageName = "@near-js/providers";
      version = "0.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/@near-js/providers/-/providers-0.0.10.tgz";
        sha512 = "c3t2+34mL5YHn93pwPwJr6LPUZbpmBPtBoyhX105R8l8QxShy4L8IHPj5ZhBowN1+Yrq6c5Cnw57SqHHqwz9tg==";
      };
    };
    "@near-js/signers-0.1.0" = {
      name = "_at_near-js_slash_signers";
      packageName = "@near-js/signers";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@near-js/signers/-/signers-0.1.0.tgz";
        sha512 = "EWnkzqLPcVzSXE4Y4HbtrJSqUEqVehn516PxCayRVRJ7bo6ytkas/U6e+J5Dn/vpH/Ny5Y/tcmt+A0s4vbCLZA==";
      };
    };
    "@near-js/transactions-1.1.0" = {
      name = "_at_near-js_slash_transactions";
      packageName = "@near-js/transactions";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@near-js/transactions/-/transactions-1.1.0.tgz";
        sha512 = "0kP8unj0RND20lP67nCtDN3fz0CvO/C9AX0EqlT5dAyi4ZQBabgVQq272RtT9xnaoA7OP6OPB3GUWGJS+MwsTw==";
      };
    };
    "@near-js/types-0.0.4" = {
      name = "_at_near-js_slash_types";
      packageName = "@near-js/types";
      version = "0.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@near-js/types/-/types-0.0.4.tgz";
        sha512 = "8TTMbLMnmyG06R5YKWuS/qFG1tOA3/9lX4NgBqQPsvaWmDsa+D+QwOkrEHDegped0ZHQwcjAXjKML1S1TyGYKg==";
      };
    };
    "@near-js/utils-0.0.5" = {
      name = "_at_near-js_slash_utils";
      packageName = "@near-js/utils";
      version = "0.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@near-js/utils/-/utils-0.0.5.tgz";
        sha512 = "0YnPruP6xZc/scIAX7E3GrTrFMNAyB9bFZOoOdA60GPzHwTTfpXsdozZvsQN4LvfFuiCDN1OEhwx7EtJh43DRw==";
      };
    };
    "@near-js/wallet-account-1.0.2" = {
      name = "_at_near-js_slash_wallet-account";
      packageName = "@near-js/wallet-account";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@near-js/wallet-account/-/wallet-account-1.0.2.tgz";
        sha512 = "bbouucpBgFtZ3bI7KvcYT8/r1q4w5UVIbbZqTUnuXpkceSQ7IxjeKCR00Iastj9EOXWAAAJBYkn0942QJjBC5w==";
      };
    };
    "@noble/curves-1.2.0" = {
      name = "_at_noble_slash_curves";
      packageName = "@noble/curves";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@noble/curves/-/curves-1.2.0.tgz";
        sha512 = "oYclrNgRaM9SsBUBVbb8M6DTV7ZHRTKugureoYEncY5c65HOmRzvSiTE3y5CYaPYJA/GVkrhXEoF0M3Ya9PMnw==";
      };
    };
    "@noble/hashes-1.3.2" = {
      name = "_at_noble_slash_hashes";
      packageName = "@noble/hashes";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@noble/hashes/-/hashes-1.3.2.tgz";
        sha512 = "MVC8EAQp7MvEcm30KWENFjgR+Mkmf+D189XJTkFIlwohU5hcBbn1ZkKq7KVTi2Hme3PMGF390DaL52beVrIihQ==";
      };
    };
    "@noble/hashes-1.3.3" = {
      name = "_at_noble_slash_hashes";
      packageName = "@noble/hashes";
      version = "1.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@noble/hashes/-/hashes-1.3.3.tgz";
        sha512 = "V7/fPHgl+jsVPXqqeOzT8egNj2iBIVt+ECeMMG8TdcnTikP3oaBtUVqpT/gYCR68aEBJSF+XbYUxStjbFMqIIA==";
      };
    };
    "@sindresorhus/is-0.14.0" = {
      name = "_at_sindresorhus_slash_is";
      packageName = "@sindresorhus/is";
      version = "0.14.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@sindresorhus/is/-/is-0.14.0.tgz";
        sha512 = "9NET910DNaIPngYnLLPeg+Ogzqsi9uM4mSboU5y6p8S5DzMTVEsJZrawi+BoDNUVBa2DhJqQYUFvMDfgU062LQ==";
      };
    };
    "@szmarczak/http-timer-1.1.2" = {
      name = "_at_szmarczak_slash_http-timer";
      packageName = "@szmarczak/http-timer";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@szmarczak/http-timer/-/http-timer-1.1.2.tgz";
        sha512 = "XIB2XbzHTN6ieIjfIMV9hlVcfPU26s2vafYWQcZHWXHOxiaRZYEDKEwdl129Zyg50+foYV2jCgtrqSA6qNuNSA==";
      };
    };
    "@types/json-schema-7.0.15" = {
      name = "_at_types_slash_json-schema";
      packageName = "@types/json-schema";
      version = "7.0.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/json-schema/-/json-schema-7.0.15.tgz";
        sha512 = "5+fP8P8MFNC+AyZCDxrB2pkZFPGzqQWUzpSeuuVLvm8VMcorNYavBqoFcxK8bQz4Qsbn4oUEEem4wDLfcysGHA==";
      };
    };
    "@types/node-11.11.6" = {
      name = "_at_types_slash_node";
      packageName = "@types/node";
      version = "11.11.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node/-/node-11.11.6.tgz";
        sha512 = "Exw4yUWMBXM3X+8oqzJNRqZSwUAaS4+7NdvHqQuFi/d+synz++xmX3QIf+BFqneW8N31R8Ky+sikfZUXq07ggQ==";
      };
    };
    "ajv-8.11.2" = {
      name = "ajv";
      packageName = "ajv";
      version = "8.11.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ajv/-/ajv-8.11.2.tgz";
        sha512 = "E4bfmKAhGiSTvMfL1Myyycaub+cUEU2/IvpylXkUu7CHBkBj1f/ikdzbD7YQ6FKUbixDxeYvB/xY4fvyroDlQg==";
      };
    };
    "ajv-formats-2.1.1" = {
      name = "ajv-formats";
      packageName = "ajv-formats";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ajv-formats/-/ajv-formats-2.1.1.tgz";
        sha512 = "Wx0Kx52hxE7C18hkMEggYlEifqWZtYaRgouJor+WMdPnQyEK13vgEWyVNup7SoeeoLMsr4kf5h6dOW11I15MUA==";
      };
    };
    "ansi-align-3.0.1" = {
      name = "ansi-align";
      packageName = "ansi-align";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-align/-/ansi-align-3.0.1.tgz";
        sha512 = "IOfwwBF5iczOjp/WeY4YxyjqAFMQoZufdQWDd19SEExbVLNXqvpzSJ/M7Za4/sCPmQ0+GRquoA7bGcINcxew6w==";
      };
    };
    "ansi-regex-5.0.1" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-5.0.1.tgz";
        sha512 = "quJQXlTSUGL2LH9SUXo8VwsY4soanhgo6LNSm84E1LBcE8s3O0wpdiRzyR9z/ZZJMlMWv37qOOb9pdJlMUEKFQ==";
      };
    };
    "ansi-styles-4.3.0" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-4.3.0.tgz";
        sha512 = "zbB9rCJAT1rbjiVDb2hqKFHNYLxgtk8NURxZ3IZwD3F6NtxbXZQCnnSi1Lkx+IDohdPlFp222wVALIheZJQSEg==";
      };
    };
    "ascii-table-0.0.9" = {
      name = "ascii-table";
      packageName = "ascii-table";
      version = "0.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/ascii-table/-/ascii-table-0.0.9.tgz";
        sha512 = "xpkr6sCDIYTPqzvjG8M3ncw1YOTaloWZOyrUmicoEifBEKzQzt+ooUpRpQ/AbOoJfO/p2ZKiyp79qHThzJDulQ==";
      };
    };
    "base-x-2.0.6" = {
      name = "base-x";
      packageName = "base-x";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/base-x/-/base-x-2.0.6.tgz";
        sha512 = "UAmjxz9KbK+YIi66xej+pZVo/vxUOh49ubEvZW5egCbxhur05pBb+hwuireQwKO4nDpsNm64/jEei17LEpsr5g==";
      };
    };
    "base-x-3.0.9" = {
      name = "base-x";
      packageName = "base-x";
      version = "3.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/base-x/-/base-x-3.0.9.tgz";
        sha512 = "H7JU6iBHTal1gp56aKoaa//YUxEaAOUiydvrV/pILqIHXTtqxSkATOnDA2u+jZ/61sD+L/412+7kzXRtWukhpQ==";
      };
    };
    "base-x-4.0.0" = {
      name = "base-x";
      packageName = "base-x";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/base-x/-/base-x-4.0.0.tgz";
        sha512 = "FuwxlW4H5kh37X/oW59pwTzzTKRzfrrQwhmyspRM7swOEZcHtDZSCt45U6oKgtuFE+WYPblePMVIPR4RZrh/hw==";
      };
    };
    "bip39-3.0.2" = {
      name = "bip39";
      packageName = "bip39";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/bip39/-/bip39-3.0.2.tgz";
        sha512 = "J4E1r2N0tUylTKt07ibXvhpT2c5pyAFgvuA5q1H9uDy6dEGpjV8jmymh3MTYJDLCNbIVClSB9FbND49I6N24MQ==";
      };
    };
    "bip39-light-1.0.7" = {
      name = "bip39-light";
      packageName = "bip39-light";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/bip39-light/-/bip39-light-1.0.7.tgz";
        sha512 = "WDTmLRQUsiioBdTs9BmSEmkJza+8xfJmptsNJjxnoq3EydSa/ZBXT6rm66KoT3PJIRYMnhSKNR7S9YL1l7R40Q==";
      };
    };
    "bn.js-5.2.1" = {
      name = "bn.js";
      packageName = "bn.js";
      version = "5.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/bn.js/-/bn.js-5.2.1.tgz";
        sha512 = "eXRvHzWyYPBuB4NBy0cmYQjGitUrtqwbvlzP3G6VFnNRbsZQIxQ10PbKKHt8gZ/HW/D/747aDl+QkDqg3KQLMQ==";
      };
    };
    "borsh-1.0.0" = {
      name = "borsh";
      packageName = "borsh";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/borsh/-/borsh-1.0.0.tgz";
        sha512 = "fSVWzzemnyfF89EPwlUNsrS5swF5CrtiN4e+h0/lLf4dz2he4L3ndM20PS9wj7ICSkXJe/TQUHdaPTq15b1mNQ==";
      };
    };
    "boxen-5.1.2" = {
      name = "boxen";
      packageName = "boxen";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/boxen/-/boxen-5.1.2.tgz";
        sha512 = "9gYgQKXx+1nP8mP7CzFyaUARhg7D3n1dF/FnErWmu9l6JvGpNUN278h0aSb+QjoiKSWG+iZ3uHrcqk0qrY9RQQ==";
      };
    };
    "bs58-4.0.0" = {
      name = "bs58";
      packageName = "bs58";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bs58/-/bs58-4.0.0.tgz";
        sha512 = "/jcGuUuSebyxwLLfKrbKnCJttxRf9PM51EnHTwmFKBxl4z1SGkoAhrfd6uZKE0dcjQTfm6XzTP8DPr1tzE4KIw==";
      };
    };
    "bs58-4.0.1" = {
      name = "bs58";
      packageName = "bs58";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/bs58/-/bs58-4.0.1.tgz";
        sha512 = "Ok3Wdf5vOIlBrgCvTq96gBkJw+JUEzdBgyaza5HLtPm7yTHkjRy8+JzNyHF7BHa0bNWOQIp3m5YF0nnFcOIKLw==";
      };
    };
    "bs58-5.0.0" = {
      name = "bs58";
      packageName = "bs58";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bs58/-/bs58-5.0.0.tgz";
        sha512 = "r+ihvQJvahgYT50JD05dyJNKlmmSlMoOGwn1lCcEzanPglg7TxYjioQUYehQ9mAR/+hOSd2jRc/Z2y5UxBymvQ==";
      };
    };
    "cacheable-request-6.1.0" = {
      name = "cacheable-request";
      packageName = "cacheable-request";
      version = "6.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cacheable-request/-/cacheable-request-6.1.0.tgz";
        sha512 = "Oj3cAGPCqOZX7Rz64Uny2GYAZNliQSqfbePrgAQ1wKAihYmCUnraBtJtKcGR4xz7wF+LoJC+ssFZvv5BgF9Igg==";
      };
    };
    "camelcase-6.3.0" = {
      name = "camelcase";
      packageName = "camelcase";
      version = "6.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/camelcase/-/camelcase-6.3.0.tgz";
        sha512 = "Gmy6FhYlCY7uOElZUSbxo2UCDH8owEk996gkbrpsgGtrJLM3J7jGxl9Ic7Qwwj4ivOE5AWZWRMecDdF7hqGjFA==";
      };
    };
    "chalk-4.1.2" = {
      name = "chalk";
      packageName = "chalk";
      version = "4.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-4.1.2.tgz";
        sha512 = "oKnbhFyRIXpUuez8iBMmyEa4nbj4IOQyuhc/wy9kY7/WVPcwIO9VA668Pu8RkO7+0G76SLROeyw9CpQ061i4mA==";
      };
    };
    "ci-info-2.0.0" = {
      name = "ci-info";
      packageName = "ci-info";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ci-info/-/ci-info-2.0.0.tgz";
        sha512 = "5tK7EtrZ0N+OLFMthtqOj4fI2Jeb88C4CAZPu25LDVUgXJ0A3Js4PMGqrn0JU1W0Mh1/Z8wZzYPxqUrXeBboCQ==";
      };
    };
    "ci-info-3.9.0" = {
      name = "ci-info";
      packageName = "ci-info";
      version = "3.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ci-info/-/ci-info-3.9.0.tgz";
        sha512 = "NIxF55hv4nSqQswkAeiOi1r83xy8JldOFDTWiug55KBu9Jnblncd2U6ViHmYgHf01TPZS77NJBhBMKdWj9HQMQ==";
      };
    };
    "cipher-base-1.0.4" = {
      name = "cipher-base";
      packageName = "cipher-base";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/cipher-base/-/cipher-base-1.0.4.tgz";
        sha512 = "Kkht5ye6ZGmwv40uUDZztayT2ThLQGfnj/T71N/XzeZeo3nf8foyW7zGTsPYkEya3m5f3cAypH+qe7YOrM1U2Q==";
      };
    };
    "cli-boxes-2.2.1" = {
      name = "cli-boxes";
      packageName = "cli-boxes";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/cli-boxes/-/cli-boxes-2.2.1.tgz";
        sha512 = "y4coMcylgSCdVinjiDBuR8PCC2bLjyGTwEmPb9NHR/QaNU6EUOXcTY/s6VjGMD6ENSEaeQYHCY0GNGS5jfMwPw==";
      };
    };
    "cliui-8.0.1" = {
      name = "cliui";
      packageName = "cliui";
      version = "8.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/cliui/-/cliui-8.0.1.tgz";
        sha512 = "BSeNnyus75C4//NQ9gQt1/csTXyo/8Sb+afLAkzAptFuMsod9HFokGNudZpi/oQV73hnVK+sR+5PVRMd+Dr7YQ==";
      };
    };
    "clone-response-1.0.3" = {
      name = "clone-response";
      packageName = "clone-response";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/clone-response/-/clone-response-1.0.3.tgz";
        sha512 = "ROoL94jJH2dUVML2Y/5PEDNaSHgeOdSDicUyS7izcF63G6sTc/FTjLub4b8Il9S8S0beOfYt0TaA5qvFK+w0wA==";
      };
    };
    "color-convert-2.0.1" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-2.0.1.tgz";
        sha512 = "RRECPsj7iu/xb5oKYcsFHSppFNnsj/52OVTRKb4zP5onXwVF3zVmmToNcOfGC+CRDpfK/U584fMg38ZHCaElKQ==";
      };
    };
    "color-name-1.1.4" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.4.tgz";
        sha512 = "dOy+3AuW3a2wNbZHIuMZpTcgjGuLU/uBL/ubcZF9OXbDo8ff4O8yVp5Bf0efS8uEoYo5q4Fx7dY9OgQGXgAsQA==";
      };
    };
    "configstore-5.0.1" = {
      name = "configstore";
      packageName = "configstore";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/configstore/-/configstore-5.0.1.tgz";
        sha512 = "aMKprgk5YhBNyH25hj8wGt2+D52Sw1DRRIzqBwLp2Ya9mFmY8KPvvtvmna8SxVR9JMZ4kzMD68N22vlaRpkeFA==";
      };
    };
    "create-hash-1.2.0" = {
      name = "create-hash";
      packageName = "create-hash";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/create-hash/-/create-hash-1.2.0.tgz";
        sha512 = "z00bCGNHDG8mHAkP7CtT1qVu+bFQUPjYq/4Iv3C3kWjTFV10zIjfSoeqXo9Asws8gwSHDGj/hl2u4OGIjapeCg==";
      };
    };
    "create-hmac-1.1.7" = {
      name = "create-hmac";
      packageName = "create-hmac";
      version = "1.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/create-hmac/-/create-hmac-1.1.7.tgz";
        sha512 = "MJG9liiZ+ogc4TzUwuvbER1JRdgvUFSB5+VR/g5h82fGaIRWMWddtKBHi7/sVhfjQZ6SehlyhvQYrcYkaUIpLg==";
      };
    };
    "crypto-random-string-2.0.0" = {
      name = "crypto-random-string";
      packageName = "crypto-random-string";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/crypto-random-string/-/crypto-random-string-2.0.0.tgz";
        sha512 = "v1plID3y9r/lPhviJ1wrXpLeyUIGAZ2SHNYTEapm7/8A9nLPoyvVp3RK/EPFqn5kEznyWgYZNsRtYYIWbuG8KA==";
      };
    };
    "debug-4.3.1" = {
      name = "debug";
      packageName = "debug";
      version = "4.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-4.3.1.tgz";
        sha512 = "doEwdvm4PCeK4K3RQN2ZC2BYUBaxwLARCqZmMjtF8a51J2Rb0xpVloFRnCODwqjpwnAoao4pelN8l3RJdv3gRQ==";
      };
    };
    "decompress-response-3.3.0" = {
      name = "decompress-response";
      packageName = "decompress-response";
      version = "3.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/decompress-response/-/decompress-response-3.3.0.tgz";
        sha512 = "BzRPQuY1ip+qDonAOz42gRm/pg9F768C+npV/4JOsxRC2sq+Rlk+Q4ZCAsOhnIaMrgarILY+RMUIvMmmX1qAEA==";
      };
    };
    "deep-extend-0.6.0" = {
      name = "deep-extend";
      packageName = "deep-extend";
      version = "0.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/deep-extend/-/deep-extend-0.6.0.tgz";
        sha512 = "LOHxIOaPYdHlJRtCQfDIVZtfw/ufM8+rVj649RIHzcm/vGwQRXFt6OPqIFWsm2XEMrNIEtWR64sY1LEKD2vAOA==";
      };
    };
    "deep-is-0.1.4" = {
      name = "deep-is";
      packageName = "deep-is";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/deep-is/-/deep-is-0.1.4.tgz";
        sha512 = "oIPzksmTg4/MriiaYGO+okXDT7ztn/w3Eptv/+gSIdMdKsJo0u4CfYNFJPy+4SKMuCqGw2wxnA+URMg3t8a/bQ==";
      };
    };
    "defer-to-connect-1.1.3" = {
      name = "defer-to-connect";
      packageName = "defer-to-connect";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/defer-to-connect/-/defer-to-connect-1.1.3.tgz";
        sha512 = "0ISdNousHvZT2EiFlZeZAHBUvSxmKswVCEf8hW7KWgG4a8MVEu/3Vb6uWYozkjylyCxe0JBIiRB1jV45S70WVQ==";
      };
    };
    "define-lazy-prop-2.0.0" = {
      name = "define-lazy-prop";
      packageName = "define-lazy-prop";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/define-lazy-prop/-/define-lazy-prop-2.0.0.tgz";
        sha512 = "Ds09qNh8yw3khSjiJjiUInaGX9xlqZDY7JVryGxdxV7NPeuqQfplOpQ66yJFZut3jLa5zOwkXw1g9EI2uKh4Og==";
      };
    };
    "depd-1.1.2" = {
      name = "depd";
      packageName = "depd";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/depd/-/depd-1.1.2.tgz";
        sha512 = "7emPTl6Dpo6JRXOXjLRxck+FlLRX5847cLKEn00PLAgc3g2hTZZgr+e4c2v6QpSmLeFP3n5yUo7ft6avBK/5jQ==";
      };
    };
    "depd-2.0.0" = {
      name = "depd";
      packageName = "depd";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/depd/-/depd-2.0.0.tgz";
        sha512 = "g7nH6P6dyDioJogAAGprGpCtVImJhpPk/roCzdb3fIh61/s/nPsfR6onyMwkCAR/OlC3yBC0lESvUoQEAssIrw==";
      };
    };
    "dot-prop-5.3.0" = {
      name = "dot-prop";
      packageName = "dot-prop";
      version = "5.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/dot-prop/-/dot-prop-5.3.0.tgz";
        sha512 = "QM8q3zDe58hqUqjraQOmzZ1LIH9SWQJTlEKCH4kJ2oQvLZk7RbQXvtDM2XEq3fwkV9CCvvH4LA0AV+ogFsBM2Q==";
      };
    };
    "duplexer3-0.1.5" = {
      name = "duplexer3";
      packageName = "duplexer3";
      version = "0.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/duplexer3/-/duplexer3-0.1.5.tgz";
        sha512 = "1A8za6ws41LQgv9HrE/66jyC5yuSjQ3L/KOpFtoBilsAK2iA2wuS5rTt1OCzIvtS2V7nVmedsUU+DGRcjBmOYA==";
      };
    };
    "emoji-regex-8.0.0" = {
      name = "emoji-regex";
      packageName = "emoji-regex";
      version = "8.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/emoji-regex/-/emoji-regex-8.0.0.tgz";
        sha512 = "MSjYzcWNOA0ewAHpz0MxpYFvwg6yjy1NG3xteoqz644VCo/RPgnr1/GGt+ic3iJTzQ8Eu3TdM14SawnVUmGE6A==";
      };
    };
    "encoding-0.1.13" = {
      name = "encoding";
      packageName = "encoding";
      version = "0.1.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/encoding/-/encoding-0.1.13.tgz";
        sha512 = "ETBauow1T35Y/WZMkio9jiM0Z5xjHHmJ4XmjZOq1l/dXz3lr2sRn87nJy20RupqSh1F2m3HHPSp8ShIPQJrJ3A==";
      };
    };
    "end-of-stream-1.4.4" = {
      name = "end-of-stream";
      packageName = "end-of-stream";
      version = "1.4.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/end-of-stream/-/end-of-stream-1.4.4.tgz";
        sha512 = "+uw1inIHVPQoaVuHzRyXd21icM+cnt4CzD5rW+NC1wjOUSTOs+Te7FOv7AhN7vS9x/oIyhLP5PR1H+phQAHu5Q==";
      };
    };
    "escalade-3.1.2" = {
      name = "escalade";
      packageName = "escalade";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/escalade/-/escalade-3.1.2.tgz";
        sha512 = "ErCHMCae19vR8vQGe50xIsVomy19rg6gFu3+r3jkEO46suLMWBksvVyoGgQV+jOfl84ZSOSlmv6Gxa89PmTGmA==";
      };
    };
    "escape-goat-2.1.1" = {
      name = "escape-goat";
      packageName = "escape-goat";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-goat/-/escape-goat-2.1.1.tgz";
        sha512 = "8/uIhbG12Csjy2JEW7D9pHbreaVaS/OpN3ycnyvElTdwM5n6GY6W6e2IPemfvGZeUMqZ9A/3GqIZMgKnBhAw/Q==";
      };
    };
    "fast-deep-equal-3.1.3" = {
      name = "fast-deep-equal";
      packageName = "fast-deep-equal";
      version = "3.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-deep-equal/-/fast-deep-equal-3.1.3.tgz";
        sha512 = "f3qQ9oQy9j2AhBe/H9VC91wLmKBCCU/gDOnKNAYG5hswO7BLKj09Hc5HYNz9cGI++xlpDCIgDaitVs03ATR84Q==";
      };
    };
    "flagged-respawn-2.0.0" = {
      name = "flagged-respawn";
      packageName = "flagged-respawn";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/flagged-respawn/-/flagged-respawn-2.0.0.tgz";
        sha512 = "Gq/a6YCi8zexmGHMuJwahTGzXlAZAOsbCVKduWXC6TlLCjjFRlExMJc4GC2NYPYZ0r/brw9P7CpRgQmlPVeOoA==";
      };
    };
    "get-caller-file-2.0.5" = {
      name = "get-caller-file";
      packageName = "get-caller-file";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-caller-file/-/get-caller-file-2.0.5.tgz";
        sha512 = "DyFP3BM/3YHTQOCUL/w0OZHR0lpKeGrxotcHWcqNEdnltqFwXVfhEBQ94eIo34AfQpo0rGki4cyIiftY06h2Fg==";
      };
    };
    "get-stream-4.1.0" = {
      name = "get-stream";
      packageName = "get-stream";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-stream/-/get-stream-4.1.0.tgz";
        sha512 = "GMat4EJ5161kIy2HevLlr4luNjBgvmj413KaQA7jt4V8B4RDsfpHk7WQ9GVqfYyyx8OS/L66Kox+rJRNklLK7w==";
      };
    };
    "get-stream-5.2.0" = {
      name = "get-stream";
      packageName = "get-stream";
      version = "5.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-stream/-/get-stream-5.2.0.tgz";
        sha512 = "nBF+F1rAZVCu/p7rjzgA+Yb4lfYXrpl7a6VmJrU8wF9I1CKvP/QwPNZHnOlwbTkY6dvtFIzFMSyQXbLoTQPRpA==";
      };
    };
    "global-dirs-3.0.1" = {
      name = "global-dirs";
      packageName = "global-dirs";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/global-dirs/-/global-dirs-3.0.1.tgz";
        sha512 = "NBcGGFbBA9s1VzD41QXDG+3++t9Mn5t1FpLdhESY6oKY4gYTFpX4wO3sqGUa0Srjtbfj3szX0RnemmrVRUdULA==";
      };
    };
    "got-9.6.0" = {
      name = "got";
      packageName = "got";
      version = "9.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/got/-/got-9.6.0.tgz";
        sha512 = "R7eWptXuGYxwijs0eV+v3o6+XH1IqVK8dJOEecQfTmkncw9AV4dcw/Dhxi8MdlqPthxxpZyizMzyg8RTmEsG+Q==";
      };
    };
    "graceful-fs-4.2.11" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.2.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.2.11.tgz";
        sha512 = "RbJ5/jmFcNNCcDV5o9eTnBLJ/HszWV0P73bc+Ff4nS/rJj+YaS6IGyiOL0VoBYX+l1Wrl3k63h/KrH+nhJ0XvQ==";
      };
    };
    "has-flag-4.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-4.0.0.tgz";
        sha512 = "EykJT/Q1KjTWctppgIAgfSO0tKVuZUjhgMr17kqTumMl6Afv3EISleU7qZUzoXDFTAHTDC4NOoG/ZxU3EvlMPQ==";
      };
    };
    "has-yarn-2.1.0" = {
      name = "has-yarn";
      packageName = "has-yarn";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-yarn/-/has-yarn-2.1.0.tgz";
        sha512 = "UqBRqi4ju7T+TqGNdqAO0PaSVGsDGJUBQvk9eUWNGRY1CFGDzYhLWoM7JQEemnlvVcv/YEmc2wNW8BC24EnUsw==";
      };
    };
    "hash-base-3.1.0" = {
      name = "hash-base";
      packageName = "hash-base";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/hash-base/-/hash-base-3.1.0.tgz";
        sha512 = "1nmYp/rhMDiE7AYkDw+lLwlAzz0AntGIe51F3RfFfEqyQ3feY2eI/NcwC6umIQVOASPMsWJLJScWKSSvzL9IVA==";
      };
    };
    "http-cache-semantics-4.1.1" = {
      name = "http-cache-semantics";
      packageName = "http-cache-semantics";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-cache-semantics/-/http-cache-semantics-4.1.1.tgz";
        sha512 = "er295DKPVsV82j5kw1Gjt+ADA/XYHsajl82cGNQG2eyoPkvgUhX+nDIyelzhIWbbsXP39EHcI6l5tYs2FYqYXQ==";
      };
    };
    "http-errors-1.7.2" = {
      name = "http-errors";
      packageName = "http-errors";
      version = "1.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-errors/-/http-errors-1.7.2.tgz";
        sha512 = "uUQBt3H/cSIVfch6i1EuPNy/YsRSOUBXTVfZ+yR7Zjez3qjBz6i9+i4zjNaoqcoFVI4lQJ5plg63TvGfRSDCRg==";
      };
    };
    "iconv-lite-0.6.3" = {
      name = "iconv-lite";
      packageName = "iconv-lite";
      version = "0.6.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.6.3.tgz";
        sha512 = "4fCk79wshMdzMp2rH06qWrJE4iolqLhCUH+OiuIgU++RB0+94NlDL81atO7GX55uUKueo0txHNtvEyI6D7WdMw==";
      };
    };
    "import-lazy-2.1.0" = {
      name = "import-lazy";
      packageName = "import-lazy";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/import-lazy/-/import-lazy-2.1.0.tgz";
        sha512 = "m7ZEHgtw69qOGw+jwxXkHlrlIPdTGkyh66zXZ1ajZbxkDBNjSY/LGbmjc7h0s2ELsUDTAhFr55TrPSSqJGPG0A==";
      };
    };
    "imurmurhash-0.1.4" = {
      name = "imurmurhash";
      packageName = "imurmurhash";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/imurmurhash/-/imurmurhash-0.1.4.tgz";
        sha512 = "JmXMZ6wuvDmLiHEml9ykzqO6lwFbof0GG4IkcGaENdCRDDmMVnny7s5HsIgHCbaq0w2MyPhDqkhTUgS2LU2PHA==";
      };
    };
    "inherits-2.0.3" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.3.tgz";
        sha512 = "x00IRNXNy63jwGkJmzPigoySHbaqpNuzKbBOmzK+g2OdZpQ9w+sxCN+VSB3ja7IAge2OP2qpfxTjeNcyjmW1uw==";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "ini-1.3.8" = {
      name = "ini";
      packageName = "ini";
      version = "1.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/ini/-/ini-1.3.8.tgz";
        sha512 = "JV/yugV2uzW5iMRSiZAyDtQd+nxtUnjeLt0acNdw98kKLrvuRVyB80tsREOE7yvGVgalhZ6RNXCmEHkUKBKxew==";
      };
    };
    "ini-2.0.0" = {
      name = "ini";
      packageName = "ini";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ini/-/ini-2.0.0.tgz";
        sha512 = "7PnF4oN3CvZF23ADhA5wRaYEQpJ8qygSkbtTXWBeXWXmEVRXK+1ITciHWwHhsjv1TmW0MgacIv6hEi5pX5NQdA==";
      };
    };
    "ip-regex-4.3.0" = {
      name = "ip-regex";
      packageName = "ip-regex";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ip-regex/-/ip-regex-4.3.0.tgz";
        sha512 = "B9ZWJxHHOHUhUjCPrMpLD4xEq35bUTClHM1S6CBU5ixQnkZmwipwgc96vAd7AAGM9TGHvJR+Uss+/Ak6UphK+Q==";
      };
    };
    "is-ci-2.0.0" = {
      name = "is-ci";
      packageName = "is-ci";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-ci/-/is-ci-2.0.0.tgz";
        sha512 = "YfJT7rkpQB0updsdHLGWrvhBJfcfzNNawYDNIyQXJz0IViGf75O8EBPKSdvw2rF+LGCsX4FZ8tcr3b19LcZq4w==";
      };
    };
    "is-ci-3.0.1" = {
      name = "is-ci";
      packageName = "is-ci";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-ci/-/is-ci-3.0.1.tgz";
        sha512 = "ZYvCgrefwqoQ6yTyYUbQu64HsITZ3NfKX1lzaEYdkTDcfKzzCI/wthRRYKkdjHKFVgNiXKAKm65Zo1pk2as/QQ==";
      };
    };
    "is-docker-2.2.1" = {
      name = "is-docker";
      packageName = "is-docker";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-docker/-/is-docker-2.2.1.tgz";
        sha512 = "F+i2BKsFrH66iaUFc0woD8sLy8getkwTwtOBjvs56Cx4CgJDeKQeqfz8wAYiSb8JOprWhHH5p77PbmYCvvUuXQ==";
      };
    };
    "is-fullwidth-code-point-3.0.0" = {
      name = "is-fullwidth-code-point";
      packageName = "is-fullwidth-code-point";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-fullwidth-code-point/-/is-fullwidth-code-point-3.0.0.tgz";
        sha512 = "zymm5+u+sCsSWyD9qNaejV3DFvhCKclKdizYaJUuHA83RLjb7nSuGnddCHGv0hk+KY7BMAlsWeK4Ueg6EV6XQg==";
      };
    };
    "is-installed-globally-0.4.0" = {
      name = "is-installed-globally";
      packageName = "is-installed-globally";
      version = "0.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-installed-globally/-/is-installed-globally-0.4.0.tgz";
        sha512 = "iwGqO3J21aaSkC7jWnHP/difazwS7SFeIqxv6wEtLU8Y5KlzFTjyqcSIT0d8s4+dDhKytsk9PJZ2BkS5eZwQRQ==";
      };
    };
    "is-npm-5.0.0" = {
      name = "is-npm";
      packageName = "is-npm";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-npm/-/is-npm-5.0.0.tgz";
        sha512 = "WW/rQLOazUq+ST/bCAVBp/2oMERWLsR7OrKyt052dNDk4DHcDE0/7QSXITlmi+VBcV13DfIbysG3tZJm5RfdBA==";
      };
    };
    "is-obj-2.0.0" = {
      name = "is-obj";
      packageName = "is-obj";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-obj/-/is-obj-2.0.0.tgz";
        sha512 = "drqDG3cbczxxEJRoOXcOjtdp1J/lyp1mNn0xaznRs8+muBhgQcrnbspox5X5fOw0HnMnbfDzvnEMEtqDEJEo8w==";
      };
    };
    "is-path-inside-3.0.3" = {
      name = "is-path-inside";
      packageName = "is-path-inside";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-path-inside/-/is-path-inside-3.0.3.tgz";
        sha512 = "Fd4gABb+ycGAmKou8eMftCupSir5lRxqf4aD/vd0cD2qc4HL07OjCeuHMr8Ro4CoMaeCKDB0/ECBOVWjTwUvPQ==";
      };
    };
    "is-typedarray-1.0.0" = {
      name = "is-typedarray";
      packageName = "is-typedarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-typedarray/-/is-typedarray-1.0.0.tgz";
        sha512 = "cyA56iCMHAh5CdzjJIa4aohJyeO1YbwLi3Jc35MmRU6poroFjIGZzUzupGiRPOjgHg9TLu43xbpwXk523fMxKA==";
      };
    };
    "is-url-1.2.4" = {
      name = "is-url";
      packageName = "is-url";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-url/-/is-url-1.2.4.tgz";
        sha512 = "ITvGim8FhRiYe4IQ5uHSkj7pVaPDrCTkNd3yq3cV7iZAcJdHTUMPMEHcqSOy9xZ9qFenQCvi+2wjH9a1nXqHww==";
      };
    };
    "is-wsl-2.2.0" = {
      name = "is-wsl";
      packageName = "is-wsl";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-wsl/-/is-wsl-2.2.0.tgz";
        sha512 = "fKzAra0rGJUUBwGBgNkHZuToZcn+TtXHpeCgmkMJMMYx1sQDYaCSyjJBSCa2nH1DGm7s3n1oBnohoVTBaN7Lww==";
      };
    };
    "is-yarn-global-0.3.0" = {
      name = "is-yarn-global";
      packageName = "is-yarn-global";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-yarn-global/-/is-yarn-global-0.3.0.tgz";
        sha512 = "VjSeb/lHmkoyd8ryPVIKvOCn4D1koMqY+vqyjjUfc3xyKtP4dYOxM44sZrnqQSzSds3xyOrUTLTC9LVCVgLngw==";
      };
    };
    "is2-2.0.9" = {
      name = "is2";
      packageName = "is2";
      version = "2.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/is2/-/is2-2.0.9.tgz";
        sha512 = "rZkHeBn9Zzq52sd9IUIV3a5mfwBY+o2HePMh0wkGBM4z4qjvy2GwVxQ6nNXSfw6MmVP6gf1QIlWjiOavhM3x5g==";
      };
    };
    "json-buffer-3.0.0" = {
      name = "json-buffer";
      packageName = "json-buffer";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-buffer/-/json-buffer-3.0.0.tgz";
        sha512 = "CuUqjv0FUZIdXkHPI8MezCnFCdaTAacej1TZYulLoAg1h/PhwkdXFN4V/gzY4g+fMBCOV2xF+rp7t2XD2ns/NQ==";
      };
    };
    "json-schema-traverse-1.0.0" = {
      name = "json-schema-traverse";
      packageName = "json-schema-traverse";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-schema-traverse/-/json-schema-traverse-1.0.0.tgz";
        sha512 = "NM8/P9n3XjXhIZn1lLhkFaACTOURQXjWhV4BA/RnOv8xvgqtqpAX9IO4mRQxSx1Rlo4tqzeqb0sOlruaOy3dug==";
      };
    };
    "keyv-3.1.0" = {
      name = "keyv";
      packageName = "keyv";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/keyv/-/keyv-3.1.0.tgz";
        sha512 = "9ykJ/46SN/9KPM/sichzQ7OvXyGDYKGTaDlKMGCAlg2UK8KRy4jb0d8sFc+0Tt0YYnThq8X2RZgCg74RPxgcVA==";
      };
    };
    "latest-version-5.1.0" = {
      name = "latest-version";
      packageName = "latest-version";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/latest-version/-/latest-version-5.1.0.tgz";
        sha512 = "weT+r0kTkRQdCdYCNtkMwWXQTMEswKrFBkm4ckQOMVhhqhIMI1UT2hMj+1iigIhgSZm5gTmrRXBNoGUgaTY1xA==";
      };
    };
    "lowercase-keys-1.0.1" = {
      name = "lowercase-keys";
      packageName = "lowercase-keys";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lowercase-keys/-/lowercase-keys-1.0.1.tgz";
        sha512 = "G2Lj61tXDnVFFOi8VZds+SoQjtQC3dgokKdDG2mTm1tx4m50NUHBOZSBwQQHyy0V12A0JTG4icfZQH+xPyh8VA==";
      };
    };
    "lowercase-keys-2.0.0" = {
      name = "lowercase-keys";
      packageName = "lowercase-keys";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lowercase-keys/-/lowercase-keys-2.0.0.tgz";
        sha512 = "tqNXrS78oMOE73NMxK4EMLQsQowWf8jKooH9g7xPavRT706R6bkQJ6DY2Te7QukaZsulxa30wQ7bk0pm4XiHmA==";
      };
    };
    "lru-cache-6.0.0" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-6.0.0.tgz";
        sha512 = "Jo6dJ04CmSjuznwJSS3pUeWmd/H0ffTlkXXgwZi+eq1UCmqQwCh+eLsYOYCwY991i2Fah4h1BEMCx4qThGbsiA==";
      };
    };
    "lru_map-0.4.1" = {
      name = "lru_map";
      packageName = "lru_map";
      version = "0.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru_map/-/lru_map-0.4.1.tgz";
        sha512 = "I+lBvqMMFfqaV8CJCISjI3wbjmwVu/VyOoU7+qtu9d7ioW5klMgsTTiUOUp+DJvfTTzKXoPbyC6YfgkNcyPSOg==";
      };
    };
    "make-dir-3.1.0" = {
      name = "make-dir";
      packageName = "make-dir";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/make-dir/-/make-dir-3.1.0.tgz";
        sha512 = "g3FeP20LNwhALb/6Cz6Dd4F2ngze0jz7tbzrD2wAV+o9FeNHe4rL+yK2md0J/fiSf1sa1ADhXqi5+oVwOM/eGw==";
      };
    };
    "md5.js-1.3.5" = {
      name = "md5.js";
      packageName = "md5.js";
      version = "1.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/md5.js/-/md5.js-1.3.5.tgz";
        sha512 = "xitP+WxNPcTTOgnTJcrhM0xvdPepipPSf3I8EIpGKeFLjt3PlJLIDG3u8EX53ZIubkb+5U2+3rELYpEhHhzdkg==";
      };
    };
    "mimic-response-1.0.1" = {
      name = "mimic-response";
      packageName = "mimic-response";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mimic-response/-/mimic-response-1.0.1.tgz";
        sha512 = "j5EctnkH7amfV/q5Hgmoal1g2QHFJRraOtmx0JpIqkxhBhI/lJSl1nMpQ45hVarwNETOoWEimndZ4QK0RHxuxQ==";
      };
    };
    "minimist-1.2.8" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.8.tgz";
        sha512 = "2yyAR8qBkN3YuheJanUpWC5U3bb5osDywNB8RzDVlDwDHbocAJveqqj1u8+SVD7jkWT4yvsHCpWqqWqAxb0zCA==";
      };
    };
    "ms-2.1.2" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.2.tgz";
        sha512 = "sGkPx+VjMtmA6MX27oA4FBFELFCZZ4S4XqeGOXCv68tT+jb3vk/RyaKWP0PTKyWtmLSM0b+adUTEvbs1PEaH2w==";
      };
    };
    "mustache-4.0.0" = {
      name = "mustache";
      packageName = "mustache";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mustache/-/mustache-4.0.0.tgz";
        sha512 = "FJgjyX/IVkbXBXYUwH+OYwQKqWpFPLaLVESd70yHjSDunwzV2hZOoTBvPf4KLoxesUzzyfTH6F784Uqd7Wm5yA==";
      };
    };
    "near-abi-0.1.1" = {
      name = "near-abi";
      packageName = "near-abi";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/near-abi/-/near-abi-0.1.1.tgz";
        sha512 = "RVDI8O+KVxRpC3KycJ1bpfVj9Zv+xvq9PlW1yIFl46GhrnLw83/72HqHGjGDjQ8DtltkcpSjY9X3YIGZ+1QyzQ==";
      };
    };
    "near-api-js-3.0.2" = {
      name = "near-api-js";
      packageName = "near-api-js";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/near-api-js/-/near-api-js-3.0.2.tgz";
        sha512 = "o8rgHH5ZV+V9grZTu4GSILupq41JyU3Mt/G6rZ2pBybHA2ozkfp9oIXKRqC4mCkbUtYLy//YoXuLRGLsRDlB2w==";
      };
    };
    "near-hd-key-1.2.1" = {
      name = "near-hd-key";
      packageName = "near-hd-key";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/near-hd-key/-/near-hd-key-1.2.1.tgz";
        sha512 = "SIrthcL5Wc0sps+2e1xGj3zceEa68TgNZDLuCx0daxmfTP7sFTB3/mtE2pYhlFsCxWoMn+JfID5E1NlzvvbRJg==";
      };
    };
    "near-seed-phrase-0.2.0" = {
      name = "near-seed-phrase";
      packageName = "near-seed-phrase";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/near-seed-phrase/-/near-seed-phrase-0.2.0.tgz";
        sha512 = "NpmrnejpY1AdlRpDZ0schJQJtfBaoUheRfiYtQpcq9TkwPgqKZCRULV5L3hHmLc0ep7KRtikbPQ9R2ztN/3cyQ==";
      };
    };
    "node-fetch-2.6.7" = {
      name = "node-fetch";
      packageName = "node-fetch";
      version = "2.6.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-fetch/-/node-fetch-2.6.7.tgz";
        sha512 = "ZjMPFEfVx5j+y2yF35Kzx5sF7kDzxuDj6ziH4FFbOp87zKDZNx8yExJIb05OGF4Nlt9IHFIMBkRl41VdvcNdbQ==";
      };
    };
    "normalize-url-4.5.1" = {
      name = "normalize-url";
      packageName = "normalize-url";
      version = "4.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/normalize-url/-/normalize-url-4.5.1.tgz";
        sha512 = "9UZCFRHQdNrfTpGg8+1INIg93B6zE0aXMVFkw1WFwvO4SlZywU6aLg5Of0Ap/PgcbSw4LNxvMWXMeugwMCX0AA==";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha512 = "lNaJgI+2Q5URQBkccEKHTQOPaXdUxnZZElQTZY0MFUAuaEqe1E+Nyvgdz/aIyNi6Z9MzO5dv1H8n58/GELp3+w==";
      };
    };
    "open-8.4.2" = {
      name = "open";
      packageName = "open";
      version = "8.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/open/-/open-8.4.2.tgz";
        sha512 = "7x81NCL719oNbsq/3mh+hVrAWmFuEYUqrq/Iw3kUzH8ReypT9QQ0BLoJS7/G9k6N81XjW4qHWtjWwe/9eLy1EQ==";
      };
    };
    "p-cancelable-1.1.0" = {
      name = "p-cancelable";
      packageName = "p-cancelable";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-cancelable/-/p-cancelable-1.1.0.tgz";
        sha512 = "s73XxOZ4zpt1edZYZzvhqFa6uvQc1vwUa0K0BdtIZgQMAJj9IbebH+JkgKZc9h+B05PKHLOTl4ajG1BmNrVZlw==";
      };
    };
    "package-json-6.5.0" = {
      name = "package-json";
      packageName = "package-json";
      version = "6.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/package-json/-/package-json-6.5.0.tgz";
        sha512 = "k3bdm2n25tkyxcjSKzB5x8kfVxlMdgsbPr0GkZcwHsLpba6cBjqCt1KlcChKEvxHIcTB1FVMuwoijZ26xex5MQ==";
      };
    };
    "pbkdf2-3.1.2" = {
      name = "pbkdf2";
      packageName = "pbkdf2";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/pbkdf2/-/pbkdf2-3.1.2.tgz";
        sha512 = "iuh7L6jA7JEGu2WxDwtQP1ddOpaJNC4KlDEFfdQajSGgGPNi4OyDc2R7QnbY2bR9QjBVGwgvTdNJZoE7RaxUMA==";
      };
    };
    "prepend-http-2.0.0" = {
      name = "prepend-http";
      packageName = "prepend-http";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/prepend-http/-/prepend-http-2.0.0.tgz";
        sha512 = "ravE6m9Atw9Z/jjttRUZ+clIXogdghyZAuWJ3qEzjT+jI/dL1ifAqhZeC5VHzQp1MSt1+jxKkFNemj/iO7tVUA==";
      };
    };
    "pump-3.0.0" = {
      name = "pump";
      packageName = "pump";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pump/-/pump-3.0.0.tgz";
        sha512 = "LwZy+p3SFs1Pytd/jYct4wpv49HiYCqd9Rlc5ZVdk0V+8Yzv6jR5Blk3TRmPL1ft69TxP0IMZGJ+WPFU2BFhww==";
      };
    };
    "punycode-2.3.1" = {
      name = "punycode";
      packageName = "punycode";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/punycode/-/punycode-2.3.1.tgz";
        sha512 = "vYt7UD1U9Wg6138shLtLOvdAu+8DsC/ilFtEVHcH+wydcSpNE20AfSOduf6MkRFahL5FY7X1oU7nKVZFtfq8Fg==";
      };
    };
    "pupa-2.1.1" = {
      name = "pupa";
      packageName = "pupa";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pupa/-/pupa-2.1.1.tgz";
        sha512 = "l1jNAspIBSFqbT+y+5FosojNpVpF94nlI+wDUpqP9enwOTfHx9f0gh5nB96vl+6yTpsJsypeNrwfzPrKuHB41A==";
      };
    };
    "randombytes-2.1.0" = {
      name = "randombytes";
      packageName = "randombytes";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/randombytes/-/randombytes-2.1.0.tgz";
        sha512 = "vYl3iOX+4CKUWuxGi9Ukhie6fsqXqS9FE2Zaic4tNFD2N2QQaXOMFbuKK4QmDHC0JO6B1Zp41J0LpT0oR68amQ==";
      };
    };
    "rc-1.2.8" = {
      name = "rc";
      packageName = "rc";
      version = "1.2.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/rc/-/rc-1.2.8.tgz";
        sha512 = "y3bGgqKj3QBdxLbLkomlohkvsA8gdAiUQlSBJnBhfn+BPxg4bc62d8TcBW15wavDfgexCgccckhcZvywyQYPOw==";
      };
    };
    "readable-stream-3.6.2" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "3.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-3.6.2.tgz";
        sha512 = "9u/sniCrY3D5WdsERHzHE4G2YCXqoG5FTHUiCC4SIbr6XcLZBY05ya9EKjYek9O5xOAwjGq+1JdGBAS7Q9ScoA==";
      };
    };
    "registry-auth-token-4.2.2" = {
      name = "registry-auth-token";
      packageName = "registry-auth-token";
      version = "4.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/registry-auth-token/-/registry-auth-token-4.2.2.tgz";
        sha512 = "PC5ZysNb42zpFME6D/XlIgtNGdTl8bBOCw90xQLVMpzuuubJKYDWFAEuUNc+Cn8Z8724tg2SDhDRrkVEsqfDMg==";
      };
    };
    "registry-url-5.1.0" = {
      name = "registry-url";
      packageName = "registry-url";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/registry-url/-/registry-url-5.1.0.tgz";
        sha512 = "8acYXXTI0AkQv6RAOjE3vOaIXZkT9wo4LOFbBKYQEEnnMNBpKqdUrI6S4NT0KPIo/WVvJ5tE/X5LF/TQUf0ekw==";
      };
    };
    "require-directory-2.1.1" = {
      name = "require-directory";
      packageName = "require-directory";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/require-directory/-/require-directory-2.1.1.tgz";
        sha512 = "fGxEI7+wsG9xrvdjsrlmL22OMTTiHRwAMroiEeMgq8gzoLC/PQr7RsRDSTLUg/bZAZtF+TVIkHc6/4RIKrui+Q==";
      };
    };
    "require-from-string-2.0.2" = {
      name = "require-from-string";
      packageName = "require-from-string";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/require-from-string/-/require-from-string-2.0.2.tgz";
        sha512 = "Xf0nWe6RseziFMu+Ap9biiUbmplq6S9/p+7w7YXP/JBHhrUDDUhwa+vANyubuqfZWTveU//DYVGsDG7RKL/vEw==";
      };
    };
    "responselike-1.0.2" = {
      name = "responselike";
      packageName = "responselike";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/responselike/-/responselike-1.0.2.tgz";
        sha512 = "/Fpe5guzJk1gPqdJLJR5u7eG/gNY4nImjbRDaVWVMRhne55TCmj2i9Q+54PBRfatRC8v/rIiv9BN0pMd9OV5EQ==";
      };
    };
    "ripemd160-2.0.2" = {
      name = "ripemd160";
      packageName = "ripemd160";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ripemd160/-/ripemd160-2.0.2.tgz";
        sha512 = "ii4iagi25WusVoiC4B4lq7pbXfAp3D9v5CwfkY33vffw2+pkDjY1D8GaN7spsxvCSx8dkPqOZCEZyfxcmJG2IA==";
      };
    };
    "safe-buffer-5.2.1" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.2.1.tgz";
        sha512 = "rp3So07KcdmmKbGvgaNxQSJr7bGVSVk5S9Eq1F+ppbRo70+YeaDxkw5Dd8NPN+GD6bjnYm2VuPuCXmpuYvmCXQ==";
      };
    };
    "safer-buffer-2.1.2" = {
      name = "safer-buffer";
      packageName = "safer-buffer";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safer-buffer/-/safer-buffer-2.1.2.tgz";
        sha512 = "YZo3K82SD7Riyi0E1EQPojLz7kpepnSQI9IyPbHHg1XXXevb5dJI7tpyN2ADxGcQbHG7vcyRHk0cbwqcQriUtg==";
      };
    };
    "semver-6.3.1" = {
      name = "semver";
      packageName = "semver";
      version = "6.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-6.3.1.tgz";
        sha512 = "BR7VvDCVHO+q2xBEWskxS6DJE1qRnb7DxzUrogb71CWoSficBxYsiAGd+Kl0mmq/MprG9yArRkyrQxTO6XjMzA==";
      };
    };
    "semver-7.6.0" = {
      name = "semver";
      packageName = "semver";
      version = "7.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-7.6.0.tgz";
        sha512 = "EnwXhrlwXMk9gKu5/flx5sv/an57AkRplG3hTK68W7FRDN+k+OWBj65M7719OkA82XLBxrcX0KSHj+X5COhOVg==";
      };
    };
    "semver-diff-3.1.1" = {
      name = "semver-diff";
      packageName = "semver-diff";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver-diff/-/semver-diff-3.1.1.tgz";
        sha512 = "GX0Ix/CJcHyB8c4ykpHGIAvLyOwOobtM/8d+TQkAd81/bEjgPHrfba41Vpesr7jX/t8Uh+R3EX9eAS5be+jQYg==";
      };
    };
    "setprototypeof-1.1.1" = {
      name = "setprototypeof";
      packageName = "setprototypeof";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/setprototypeof/-/setprototypeof-1.1.1.tgz";
        sha512 = "JvdAWfbXeIGaZ9cILp38HntZSFSo3mWg6xGcJJsd+d4aRMOqauag1C63dJfDw7OaMYwEbHMOxEZ1lqVRYP2OAw==";
      };
    };
    "sha.js-2.4.11" = {
      name = "sha.js";
      packageName = "sha.js";
      version = "2.4.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/sha.js/-/sha.js-2.4.11.tgz";
        sha512 = "QMEp5B7cftE7APOjk5Y6xgrbWu+WkLVQwk8JNjZ8nKRciZaByEW6MubieAiToS7+dwvrjGhH8jRXz3MVd0AYqQ==";
      };
    };
    "signal-exit-3.0.7" = {
      name = "signal-exit";
      packageName = "signal-exit";
      version = "3.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/signal-exit/-/signal-exit-3.0.7.tgz";
        sha512 = "wnD2ZE+l+SPC/uoS0vXeE9L1+0wuaMqKlfz9AMUo38JsyLSBWSFcHR1Rri62LZc12vLr1gb3jl7iwQhgwpAbGQ==";
      };
    };
    "statuses-1.5.0" = {
      name = "statuses";
      packageName = "statuses";
      version = "1.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/statuses/-/statuses-1.5.0.tgz";
        sha512 = "OpZ3zP+jT1PI7I8nemJX4AKmAX070ZkYPVWV/AaKTJl+tXCTGyVdC1a4SL8RUQYEwk/f34ZX8UTykN68FwrqAA==";
      };
    };
    "stoppable-1.1.0" = {
      name = "stoppable";
      packageName = "stoppable";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/stoppable/-/stoppable-1.1.0.tgz";
        sha512 = "KXDYZ9dszj6bzvnEMRYvxgeTHU74QBFL54XKtP3nyMuJ81CFYtABZ3bAzL2EdFUaEwJOBOgENyFj3R7oTzDyyw==";
      };
    };
    "string-width-4.2.3" = {
      name = "string-width";
      packageName = "string-width";
      version = "4.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-width/-/string-width-4.2.3.tgz";
        sha512 = "wKyQRQpjJ0sIp62ErSZdGsjMJWsap5oRNihHhu6G7JVO/9jIB6UyevL+tXuOqrng8j/cxKTWyWUwvSTriiZz/g==";
      };
    };
    "string_decoder-1.3.0" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.3.0.tgz";
        sha512 = "hkRX8U1WjJFd8LsDJ2yQ/wWWxaopEsABU1XfkM8A+j0+85JAGppt16cr1Whg6KIbb4okU6Mql6BOj+uup/wKeA==";
      };
    };
    "strip-ansi-6.0.1" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-6.0.1.tgz";
        sha512 = "Y38VPSHcqkFrCpFnQ9vuSXmquuv5oXOKpGeT6aGrr3o3Gc9AlVa6JBfUSOCnbxGGZF+/0ooI7KrPuUSztUdU5A==";
      };
    };
    "strip-json-comments-2.0.1" = {
      name = "strip-json-comments";
      packageName = "strip-json-comments";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-json-comments/-/strip-json-comments-2.0.1.tgz";
        sha512 = "4gB8na07fecVVkOI6Rs4e7T6NOTki5EmL7TUduTs6bu3EdnSycntVJ4re8kgZA+wx9IueI2Y11bfbgwtzuE0KQ==";
      };
    };
    "supports-color-7.2.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "7.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-7.2.0.tgz";
        sha512 = "qpCAvRl9stuOHveKsn7HncJRvv501qIacKzQlO/+Lwxc9+0q2wLyv4Dfvt80/DPn2pqOBsJdDiogXGR9+OvwRw==";
      };
    };
    "tcp-port-used-1.0.2" = {
      name = "tcp-port-used";
      packageName = "tcp-port-used";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/tcp-port-used/-/tcp-port-used-1.0.2.tgz";
        sha512 = "l7ar8lLUD3XS1V2lfoJlCBaeoaWo/2xfYt81hM7VlvR4RrMVFqfmzfhLVk40hAb368uitje5gPtBRL1m/DGvLA==";
      };
    };
    "to-readable-stream-1.0.0" = {
      name = "to-readable-stream";
      packageName = "to-readable-stream";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-readable-stream/-/to-readable-stream-1.0.0.tgz";
        sha512 = "Iq25XBt6zD5npPhlLVXGFN3/gyR2/qODcKNNyTMd4vbm39HUaOiAM4PMq0eMVC/Tkxz+Zjdsc55g9yyz+Yq00Q==";
      };
    };
    "toidentifier-1.0.0" = {
      name = "toidentifier";
      packageName = "toidentifier";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/toidentifier/-/toidentifier-1.0.0.tgz";
        sha512 = "yaOH/Pk/VEhBWWTlhI+qXxDFXlejDGcQipMlyxda9nthulaxLZUNcUqFxokp0vcYnvteJln5FNQDRrxj3YcbVw==";
      };
    };
    "tr46-0.0.3" = {
      name = "tr46";
      packageName = "tr46";
      version = "0.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/tr46/-/tr46-0.0.3.tgz";
        sha512 = "N3WMsuqV66lT30CrXNbEjx4GEwlow3v6rr4mCcv6prnfwhS01rkgyFdjPNBYd9br7LpXV1+Emh01fHnq2Gdgrw==";
      };
    };
    "tweetnacl-1.0.3" = {
      name = "tweetnacl";
      packageName = "tweetnacl";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/tweetnacl/-/tweetnacl-1.0.3.tgz";
        sha512 = "6rt+RN7aOi1nGMyC4Xa5DdYiukl2UWCbcJft7YhxReBGQD7OAM8Pbxw6YMo4r2diNEA8FEmu32YOn9rhaiE5yw==";
      };
    };
    "type-fest-0.20.2" = {
      name = "type-fest";
      packageName = "type-fest";
      version = "0.20.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/type-fest/-/type-fest-0.20.2.tgz";
        sha512 = "Ne+eE4r0/iWnpAxD852z3A+N0Bt5RN//NjJwRd2VFHEmrywxf5vsZlh4R6lixl6B+wz/8d+maTSAkN1FIkI3LQ==";
      };
    };
    "typedarray-to-buffer-3.1.5" = {
      name = "typedarray-to-buffer";
      packageName = "typedarray-to-buffer";
      version = "3.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/typedarray-to-buffer/-/typedarray-to-buffer-3.1.5.tgz";
        sha512 = "zdu8XMNEDepKKR+XYOXAVPtWui0ly0NtohUscw+UmaHiAWT8hrV1rr//H6V+0DvJ3OQ19S979M0laLfX8rm82Q==";
      };
    };
    "unique-string-2.0.0" = {
      name = "unique-string";
      packageName = "unique-string";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/unique-string/-/unique-string-2.0.0.tgz";
        sha512 = "uNaeirEPvpZWSgzwsPGtU2zVSTrn/8L5q/IexZmH0eH6SA73CmAA5U4GwORTxQAZs95TAXLNqeLoPPNO5gZfWg==";
      };
    };
    "update-notifier-5.1.0" = {
      name = "update-notifier";
      packageName = "update-notifier";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/update-notifier/-/update-notifier-5.1.0.tgz";
        sha512 = "ItnICHbeMh9GqUy31hFPrD1kcuZ3rpxDZbf4KUDavXwS0bW5m7SLbDQpGX3UYr072cbrF5hFUs3r5tUsPwjfHw==";
      };
    };
    "uri-js-4.4.1" = {
      name = "uri-js";
      packageName = "uri-js";
      version = "4.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/uri-js/-/uri-js-4.4.1.tgz";
        sha512 = "7rKUyy33Q1yc98pQ1DAmLtwX109F7TIfWlW1Ydo8Wl1ii1SeHieeh0HHfPeL2fMXK6z0s8ecKs9frCuLJvndBg==";
      };
    };
    "url-parse-lax-3.0.0" = {
      name = "url-parse-lax";
      packageName = "url-parse-lax";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/url-parse-lax/-/url-parse-lax-3.0.0.tgz";
        sha512 = "NjFKA0DidqPa5ciFcSrXnAltTtzz84ogy+NebPvfEgAck0+TNg4UJ4IN+fB7zRZfbgUf0syOo9MDxFkDSMuFaQ==";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha512 = "EPD5q1uXyFxJpCrLnCc1nHnq3gOa6DZBocAIiI2TaSCA7VCJ1UJDMagCzIkXNsUYfD1daK//LTEQ8xiIbrHtcw==";
      };
    };
    "v8flags-4.0.1" = {
      name = "v8flags";
      packageName = "v8flags";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/v8flags/-/v8flags-4.0.1.tgz";
        sha512 = "fcRLaS4H/hrZk9hYwbdRM35D0U8IYMfEClhXxCivOojl+yTRAZH3Zy2sSy6qVCiGbV9YAtPssP6jaChqC9vPCg==";
      };
    };
    "webidl-conversions-3.0.1" = {
      name = "webidl-conversions";
      packageName = "webidl-conversions";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/webidl-conversions/-/webidl-conversions-3.0.1.tgz";
        sha512 = "2JAn3z8AR6rjK8Sm8orRC0h/bcl/DqL7tRPdGZ4I1CjdF+EaMLmYxBHyXuKL849eucPFhvBoxMsflfOb8kxaeQ==";
      };
    };
    "whatwg-url-5.0.0" = {
      name = "whatwg-url";
      packageName = "whatwg-url";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/whatwg-url/-/whatwg-url-5.0.0.tgz";
        sha512 = "saE57nupxk6v3HY35+jzBwYa0rKSy0XR8JSxZPwgLr7ys0IBzhGviA1/TUGJLmSVqs8pb9AnvICXEuOHLprYTw==";
      };
    };
    "widest-line-3.1.0" = {
      name = "widest-line";
      packageName = "widest-line";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/widest-line/-/widest-line-3.1.0.tgz";
        sha512 = "NsmoXalsWVDMGupxZ5R08ka9flZjjiLvHVAWYOKtiKM8ujtZWr9cRffak+uSE48+Ob8ObalXpwyeUiyDD6QFgg==";
      };
    };
    "wrap-ansi-7.0.0" = {
      name = "wrap-ansi";
      packageName = "wrap-ansi";
      version = "7.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrap-ansi/-/wrap-ansi-7.0.0.tgz";
        sha512 = "YVGIj2kamLSTxw6NsZjoBxfSwsn0ycdesmc4p+Q21c5zPuZ1pl+NfxVdxPtdHvmNVOQ6XSYG4AUtyt/Fi7D16Q==";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha512 = "l4Sp/DRseor9wL6EvV2+TuQn63dMkPjZ/sp9XkghTEbV9KlPS1xUsZ3u7/IQO4wxtcFB4bgpQPRcR3QCvezPcQ==";
      };
    };
    "write-file-atomic-3.0.3" = {
      name = "write-file-atomic";
      packageName = "write-file-atomic";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/write-file-atomic/-/write-file-atomic-3.0.3.tgz";
        sha512 = "AvHcyZ5JnSfq3ioSyjrBkH9yW4m7Ayk8/9My/DD9onKeu/94fwrMocemO2QAJFAlnnDN+ZDS+ZjAR5ua1/PV/Q==";
      };
    };
    "xdg-basedir-4.0.0" = {
      name = "xdg-basedir";
      packageName = "xdg-basedir";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/xdg-basedir/-/xdg-basedir-4.0.0.tgz";
        sha512 = "PSNhEJDejZYV7h50BohL09Er9VaIefr2LMAf3OEmpCkjOi34eYyQYAXUTjEQtZJTKcF0E2UKTh+osDLsgNim9Q==";
      };
    };
    "y18n-5.0.8" = {
      name = "y18n";
      packageName = "y18n";
      version = "5.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/y18n/-/y18n-5.0.8.tgz";
        sha512 = "0pfFzegeDWJHJIAmTLRP2DwHjdF5s7jo9tuztdQxAhINCdvS+3nGINqPd00AphqJR/0LhANUS6/+7SCb98YOfA==";
      };
    };
    "yallist-4.0.0" = {
      name = "yallist";
      packageName = "yallist";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yallist/-/yallist-4.0.0.tgz";
        sha512 = "3wdGidZyq5PB084XLES5TpOSRA3wjXAlIWMhum2kRcv/41Sn2emQ0dycQW4uZXLejwKvg6EsvbdlVL+FYEct7A==";
      };
    };
    "yargs-17.7.2" = {
      name = "yargs";
      packageName = "yargs";
      version = "17.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/yargs/-/yargs-17.7.2.tgz";
        sha512 = "7dSzzRQ++CKnNI/krKnYRV7JKKPUXMEh61soaHKg9mrWEhzFWhFnxPxGl+69cD1Ou63C13NUPCnmIcrvqCuM6w==";
      };
    };
    "yargs-parser-21.1.1" = {
      name = "yargs-parser";
      packageName = "yargs-parser";
      version = "21.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/yargs-parser/-/yargs-parser-21.1.1.tgz";
        sha512 = "tVpsJW7DdjecAiFpbIB1e3qxIQsE6NoPc5/eTdrbbIC4h0LVsWhnoa3g+m2HclBIujHzsxZ4VJVA+GUuc2/LBw==";
      };
    };
  };
in
{
  near-cli = nodeEnv.buildNodePackage {
    name = "near-cli";
    packageName = "near-cli";
    version = "4.0.4";
    src = fetchurl {
      url = "https://registry.npmjs.org/near-cli/-/near-cli-4.0.4.tgz";
      sha512 = "cFyUMVTFo3sEDHxY0/PZueFJL3ZMaHd/6oGJ+0DuTZEiGIz3fJqW5avqmsl2t6c88l/QehIFH9JeMc0H8F3CWg==";
    };
    dependencies = [
      sources."@near-js/accounts-1.0.2"
      sources."@near-js/crypto-1.2.0"
      sources."@near-js/keystores-0.0.8"
      sources."@near-js/keystores-browser-0.0.8"
      sources."@near-js/keystores-node-0.0.8"
      sources."@near-js/providers-0.0.10"
      (sources."@near-js/signers-0.1.0" // {
        dependencies = [
          sources."@noble/hashes-1.3.3"
        ];
      })
      (sources."@near-js/transactions-1.1.0" // {
        dependencies = [
          sources."@noble/hashes-1.3.3"
        ];
      })
      sources."@near-js/types-0.0.4"
      (sources."@near-js/utils-0.0.5" // {
        dependencies = [
          sources."base-x-2.0.6"
          sources."bs58-4.0.0"
        ];
      })
      sources."@near-js/wallet-account-1.0.2"
      sources."@noble/curves-1.2.0"
      sources."@noble/hashes-1.3.2"
      sources."@sindresorhus/is-0.14.0"
      sources."@szmarczak/http-timer-1.1.2"
      sources."@types/json-schema-7.0.15"
      sources."@types/node-11.11.6"
      sources."ajv-8.11.2"
      sources."ajv-formats-2.1.1"
      sources."ansi-align-3.0.1"
      sources."ansi-regex-5.0.1"
      sources."ansi-styles-4.3.0"
      sources."ascii-table-0.0.9"
      sources."base-x-4.0.0"
      sources."bip39-3.0.2"
      sources."bip39-light-1.0.7"
      sources."bn.js-5.2.1"
      sources."borsh-1.0.0"
      sources."boxen-5.1.2"
      sources."bs58-5.0.0"
      (sources."cacheable-request-6.1.0" // {
        dependencies = [
          sources."get-stream-5.2.0"
          sources."lowercase-keys-2.0.0"
        ];
      })
      sources."camelcase-6.3.0"
      sources."chalk-4.1.2"
      sources."ci-info-3.9.0"
      sources."cipher-base-1.0.4"
      sources."cli-boxes-2.2.1"
      sources."cliui-8.0.1"
      sources."clone-response-1.0.3"
      sources."color-convert-2.0.1"
      sources."color-name-1.1.4"
      sources."configstore-5.0.1"
      sources."create-hash-1.2.0"
      sources."create-hmac-1.1.7"
      sources."crypto-random-string-2.0.0"
      sources."debug-4.3.1"
      sources."decompress-response-3.3.0"
      sources."deep-extend-0.6.0"
      sources."deep-is-0.1.4"
      sources."defer-to-connect-1.1.3"
      sources."define-lazy-prop-2.0.0"
      sources."depd-2.0.0"
      sources."dot-prop-5.3.0"
      sources."duplexer3-0.1.5"
      sources."emoji-regex-8.0.0"
      sources."encoding-0.1.13"
      sources."end-of-stream-1.4.4"
      sources."escalade-3.1.2"
      sources."escape-goat-2.1.1"
      sources."fast-deep-equal-3.1.3"
      sources."flagged-respawn-2.0.0"
      sources."get-caller-file-2.0.5"
      sources."get-stream-4.1.0"
      sources."global-dirs-3.0.1"
      sources."got-9.6.0"
      sources."graceful-fs-4.2.11"
      sources."has-flag-4.0.0"
      sources."has-yarn-2.1.0"
      (sources."hash-base-3.1.0" // {
        dependencies = [
          sources."inherits-2.0.4"
        ];
      })
      sources."http-cache-semantics-4.1.1"
      (sources."http-errors-1.7.2" // {
        dependencies = [
          sources."depd-1.1.2"
        ];
      })
      sources."iconv-lite-0.6.3"
      sources."import-lazy-2.1.0"
      sources."imurmurhash-0.1.4"
      sources."inherits-2.0.3"
      sources."ini-2.0.0"
      sources."ip-regex-4.3.0"
      sources."is-ci-3.0.1"
      sources."is-docker-2.2.1"
      sources."is-fullwidth-code-point-3.0.0"
      sources."is-installed-globally-0.4.0"
      sources."is-npm-5.0.0"
      sources."is-obj-2.0.0"
      sources."is-path-inside-3.0.3"
      sources."is-typedarray-1.0.0"
      sources."is-url-1.2.4"
      sources."is-wsl-2.2.0"
      sources."is-yarn-global-0.3.0"
      sources."is2-2.0.9"
      sources."json-buffer-3.0.0"
      sources."json-schema-traverse-1.0.0"
      sources."keyv-3.1.0"
      sources."latest-version-5.1.0"
      sources."lowercase-keys-1.0.1"
      sources."lru-cache-6.0.0"
      sources."lru_map-0.4.1"
      (sources."make-dir-3.1.0" // {
        dependencies = [
          sources."semver-6.3.1"
        ];
      })
      sources."md5.js-1.3.5"
      sources."mimic-response-1.0.1"
      sources."minimist-1.2.8"
      sources."ms-2.1.2"
      sources."mustache-4.0.0"
      sources."near-abi-0.1.1"
      sources."near-api-js-3.0.2"
      sources."near-hd-key-1.2.1"
      (sources."near-seed-phrase-0.2.0" // {
        dependencies = [
          sources."base-x-3.0.9"
          sources."bs58-4.0.1"
        ];
      })
      sources."node-fetch-2.6.7"
      sources."normalize-url-4.5.1"
      sources."once-1.4.0"
      sources."open-8.4.2"
      sources."p-cancelable-1.1.0"
      (sources."package-json-6.5.0" // {
        dependencies = [
          sources."semver-6.3.1"
        ];
      })
      sources."pbkdf2-3.1.2"
      sources."prepend-http-2.0.0"
      sources."pump-3.0.0"
      sources."punycode-2.3.1"
      sources."pupa-2.1.1"
      sources."randombytes-2.1.0"
      (sources."rc-1.2.8" // {
        dependencies = [
          sources."ini-1.3.8"
        ];
      })
      sources."readable-stream-3.6.2"
      sources."registry-auth-token-4.2.2"
      sources."registry-url-5.1.0"
      sources."require-directory-2.1.1"
      sources."require-from-string-2.0.2"
      sources."responselike-1.0.2"
      sources."ripemd160-2.0.2"
      sources."safe-buffer-5.2.1"
      sources."safer-buffer-2.1.2"
      sources."semver-7.6.0"
      (sources."semver-diff-3.1.1" // {
        dependencies = [
          sources."semver-6.3.1"
        ];
      })
      sources."setprototypeof-1.1.1"
      sources."sha.js-2.4.11"
      sources."signal-exit-3.0.7"
      sources."statuses-1.5.0"
      sources."stoppable-1.1.0"
      sources."string-width-4.2.3"
      sources."string_decoder-1.3.0"
      sources."strip-ansi-6.0.1"
      sources."strip-json-comments-2.0.1"
      sources."supports-color-7.2.0"
      sources."tcp-port-used-1.0.2"
      sources."to-readable-stream-1.0.0"
      sources."toidentifier-1.0.0"
      sources."tr46-0.0.3"
      sources."tweetnacl-1.0.3"
      sources."type-fest-0.20.2"
      sources."typedarray-to-buffer-3.1.5"
      sources."unique-string-2.0.0"
      (sources."update-notifier-5.1.0" // {
        dependencies = [
          sources."ci-info-2.0.0"
          sources."is-ci-2.0.0"
        ];
      })
      sources."uri-js-4.4.1"
      sources."url-parse-lax-3.0.0"
      sources."util-deprecate-1.0.2"
      sources."v8flags-4.0.1"
      sources."webidl-conversions-3.0.1"
      sources."whatwg-url-5.0.0"
      sources."widest-line-3.1.0"
      sources."wrap-ansi-7.0.0"
      sources."wrappy-1.0.2"
      sources."write-file-atomic-3.0.3"
      sources."xdg-basedir-4.0.0"
      sources."y18n-5.0.8"
      sources."yallist-4.0.0"
      sources."yargs-17.7.2"
      sources."yargs-parser-21.1.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Simple CLI for interacting with NEAR Protocol";
      homepage = "https://github.com/near/near-cli#readme";
      license = "(MIT AND Apache-2.0)";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
