name: system info checker

concurrency:
  group: system-info-${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v3
    - name: Check System Info Update
      run: ./scripts/system-info check
