name: "Update near-config"
on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron:  '38 0 * * *'
permissions:
  contents: write
  pull-requests: write
jobs:
  updateNeardConfig:
    strategy:
      matrix:
        network: [mainnet, testnet]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'main'
      - name: Upgrade neard-configuration
        run: |
          bash -x ./.github/workflows/update-neard-configuration.sh ${{matrix.network}}
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Upgrade near configuration for ${{matrix.network}}
          branch: near-config-${{matrix.network}}
          delete-branch: true
          title: Upgrade near configuration for ${{matrix.network}}
          body: |
            Also check if the new configuration is still valid

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
  updateGenesisConfig:
    strategy:
      matrix:
        network: [mainnet]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upgrade neard configuration
        run: |
          curl https://s3-us-west-1.amazonaws.com/build.nearprotocol.com/nearcore-deploy/${{matrix.network}}/genesis.json > nix/modules/neard/${{matrix.network}}/genesis.json
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Upgrade near configuration for ${{matrix.network}}
          branch: near-genesis-${{matrix.network}}
          delete-branch: true
          title: Upgrade genesis.json for ${{matrix.network}}
          body: |
            Also check if the new configuration is still valid

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
